import type { CardDefinition, DeckEntry, HeroId, PreparedDecks } from '../domain/model';

export const cards: CardDefinition[] = [
  {
    id: 'b_slash',
    name: '먹의 일격',
    owner: 'brush',
    cost: 1,
    target: 'enemy',
    rarity: '일반',
    school: '무공',
    type: '공격',
    art: 0,
    description: '피해 12. 묵흔 1을 얻습니다.',
    keywords: [],
    effects: [
      { kind: 'damage', amount: 12 },
      { kind: 'ink', amount: 1 },
    ],
  },
  {
    id: 'b_guard',
    name: '수묵 장막',
    owner: 'brush',
    cost: 1,
    target: 'self',
    rarity: '일반',
    school: '무공',
    type: '기술',
    art: 0,
    description: '보호막 9. 묵흔 1을 얻습니다.',
    keywords: [],
    effects: [
      { kind: 'block', amount: 9, self: true },
      { kind: 'ink', amount: 1 },
    ],
  },
  {
    id: 'b_double',
    name: '쌍획',
    owner: 'brush',
    cost: 1,
    target: 'enemy',
    rarity: '고급',
    school: '무공',
    type: '공격',
    art: 0,
    description: '피해 6을 두 번 줍니다.',
    keywords: [],
    effects: [{ kind: 'damage', amount: 6, hits: 2 }],
  },
  {
    id: 'b_mark',
    name: '파묵',
    owner: 'brush',
    cost: 1,
    target: 'enemy',
    rarity: '고급',
    school: '무공',
    type: '공격',
    art: 0,
    description: '피해 8. 취약 2를 부여합니다.',
    keywords: [],
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'status', status: 'vulnerable', amount: 2 },
    ],
  },
  {
    id: 'b_dragon',
    name: '먹룡의 궤적',
    owner: 'brush',
    cost: 2,
    target: 'none',
    rarity: '희귀',
    school: '무공',
    type: '공격',
    art: 5,
    description: '모든 적에게 피해 10 + 묵흔 × 2.',
    keywords: ['exhaust'],
    effects: [{ kind: 'damage', amount: 10, all: true, inkScale: 2 }],
  },
  {
    id: 'b_flow',
    name: '필세',
    owner: 'brush',
    cost: 1,
    target: 'self',
    rarity: '고급',
    school: '무공',
    type: '지속',
    art: 0,
    description: '턴 시작마다 묵흔 1을 얻습니다.',
    keywords: [],
    effects: [{ kind: 'power', power: 'flow', amount: 1 }],
  },
  {
    id: 'm_fire',
    name: '화염탄',
    owner: 'mage',
    cost: 1,
    target: 'enemy',
    rarity: '일반',
    school: '마법',
    type: '공격',
    art: 1,
    description: '피해 8. 화상 3을 부여합니다.',
    keywords: [],
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'status', status: 'burn', amount: 3 },
    ],
  },
  {
    id: 'm_ice',
    name: '빙결파',
    owner: 'mage',
    cost: 1,
    target: 'enemy',
    rarity: '일반',
    school: '마법',
    type: '공격',
    art: 2,
    description: '피해 6. 약화 2를 부여합니다.',
    keywords: [],
    effects: [
      { kind: 'damage', amount: 6 },
      { kind: 'status', status: 'weak', amount: 2 },
    ],
  },
  {
    id: 'm_bolt',
    name: '연쇄 번개',
    owner: 'mage',
    cost: 2,
    target: 'none',
    rarity: '고급',
    school: '마법',
    type: '공격',
    art: 4,
    description: '모든 적에게 피해 11.',
    keywords: [],
    effects: [{ kind: 'damage', amount: 11, all: true }],
  },
  {
    id: 'm_mana',
    name: '원소 순환',
    owner: 'mage',
    cost: 0,
    target: 'self',
    rarity: '고급',
    school: '마법',
    type: '기술',
    art: 4,
    description: '에너지 1. 카드를 1장 뽑습니다. 소멸.',
    keywords: ['exhaust'],
    effects: [
      { kind: 'energy', amount: 1 },
      { kind: 'draw', amount: 1 },
    ],
  },
  {
    id: 'k_guard',
    name: '성광의 수호',
    owner: 'knight',
    cost: 1,
    target: 'ally',
    rarity: '일반',
    school: '마법',
    type: '기술',
    art: 3,
    description: '아군 하나에게 보호막 14.',
    keywords: [],
    effects: [{ kind: 'block', amount: 14 }],
  },
  {
    id: 'k_oath',
    name: '방패의 서약',
    owner: 'knight',
    cost: 1,
    target: 'self',
    rarity: '고급',
    school: '무공',
    type: '기술',
    art: 3,
    description: '보호막 10. 도발 1. 반격 3을 얻습니다.',
    keywords: [],
    effects: [
      { kind: 'block', amount: 10, self: true },
      { kind: 'status', status: 'taunt', amount: 1, self: true },
      { kind: 'status', status: 'thorns', amount: 3, self: true },
    ],
  },
  {
    id: 'k_heal',
    name: '새벽의 기도',
    owner: 'knight',
    cost: 1,
    target: 'ally',
    rarity: '고급',
    school: '마법',
    type: '기술',
    art: 3,
    description: '체력 10 회복. 소멸.',
    keywords: ['exhaust'],
    effects: [{ kind: 'heal', amount: 10 }],
  },
  {
    id: 'k_ward',
    name: '빛의 결계',
    owner: 'knight',
    cost: 2,
    target: 'self',
    rarity: '희귀',
    school: '마법',
    type: '지속',
    art: 3,
    description: '턴 시작마다 모든 아군이 보호막 3을 얻습니다.',
    keywords: [],
    effects: [{ kind: 'power', power: 'ward', amount: 3 }],
  },
  {
    id: 'c_strike',
    name: '기본 초식',
    owner: 'common',
    cost: 1,
    target: 'enemy',
    rarity: '일반',
    school: '무공',
    type: '공격',
    art: 0,
    description: '피해 9.',
    keywords: [],
    effects: [{ kind: 'damage', amount: 9 }],
  },
  {
    id: 'c_guard',
    name: '호흡 가다듬기',
    owner: 'common',
    cost: 1,
    target: 'self',
    rarity: '일반',
    school: '무공',
    type: '기술',
    art: 3,
    description: '보호막 8.',
    keywords: [],
    effects: [{ kind: 'block', amount: 8, self: true }],
  },
  {
    id: 'c_focus',
    name: '일점 집중',
    owner: 'common',
    cost: 0,
    target: 'self',
    rarity: '고급',
    school: '무공',
    type: '기술',
    art: 4,
    description: '손패 1장을 버린 뒤 2장을 뽑습니다.',
    keywords: [],
    effects: [
      { kind: 'choice', mode: 'discard', count: 1 },
      { kind: 'draw', amount: 2 },
    ],
  },
  {
    id: 'c_insight',
    name: '기맥 읽기',
    owner: 'common',
    cost: 0,
    target: 'self',
    rarity: '고급',
    school: '무공',
    type: '기술',
    art: 2,
    description: '위쪽 3장을 보고 원하는 카드를 버립니다. 보존.',
    keywords: ['retain'],
    effects: [{ kind: 'choice', mode: 'scry', count: 3 }],
  },
  {
    id: 'c_break',
    name: '흐름 끊기',
    owner: 'common',
    cost: 1,
    target: 'enemy',
    rarity: '고급',
    school: '무공',
    type: '공격',
    art: 0,
    description: '피해 7. 적의 차지를 취소합니다.',
    keywords: [],
    effects: [{ kind: 'damage', amount: 7 }, { kind: 'interrupt' }],
  },
  {
    id: 'c_resolve',
    name: '결의',
    owner: 'common',
    cost: 1,
    target: 'self',
    rarity: '고급',
    school: '무공',
    type: '기술',
    art: 3,
    description: '힘 2. 소멸. 선천성.',
    keywords: ['exhaust', 'innate'],
    effects: [{ kind: 'status', status: 'strength', amount: 2, self: true }],
  },
];
export const cardById: Record<string, CardDefinition> = Object.fromEntries(
  cards.map((card) => [card.id, card]),
);
if (new Set(cards.map((c) => c.id)).size !== cards.length) throw new Error('중복 카드 ID');
export const heroes: Record<
  HeroId,
  { name: string; role: string; art: number; maxHp: number; quote: string }
> = {
  brush: {
    name: '연묵',
    role: '붓 검객',
    art: 0,
    maxHp: 80,
    quote: '한 획으로, 돌아갈 길을 그린다.',
  },
  mage: {
    name: '리엔',
    role: '원소술사',
    art: 1,
    maxHp: 64,
    quote: '세 갈래 흐름도, 끝내 하나로.',
  },
  knight: {
    name: '세라',
    role: '신성기사',
    art: 2,
    maxHp: 96,
    quote: '당신이 나아갈 곳에, 나의 방패를.',
  },
};
export const heroIds: HeroId[] = ['brush', 'mage', 'knight'];
export function initialDecks(): PreparedDecks {
  const make = (owner: string, ids: string[]): DeckEntry[] =>
    ids.map((definitionId, i) => ({ id: `${owner}-${i}`, definitionId }));
  return {
    brush: make('brush', [
      'b_slash',
      'b_slash',
      'b_slash',
      'b_guard',
      'b_guard',
      'b_double',
      'b_double',
      'b_mark',
      'b_dragon',
      'b_flow',
    ]),
    mage: make('mage', [
      'm_fire',
      'm_fire',
      'm_fire',
      'm_ice',
      'm_ice',
      'm_ice',
      'm_bolt',
      'm_bolt',
      'm_mana',
      'm_mana',
    ]),
    knight: make('knight', [
      'k_guard',
      'k_guard',
      'k_guard',
      'k_guard',
      'k_oath',
      'k_oath',
      'k_heal',
      'k_heal',
      'k_ward',
      'k_ward',
    ]),
    common: make('common', [
      ...Array<string>(8).fill('c_strike'),
      ...Array<string>(8).fill('c_guard'),
      'c_focus',
      'c_insight',
      'c_break',
      'c_resolve',
    ]),
  };
}
